INSERT INTO tbl_attribute
VALUES
    (1, 0, "màu sắc"),
    (2, 0, "kích thước"),
    (3, 0, "phân loại"),
    (4, 0, "color"),
    (5, 0, "size")

INSERT INTO tbl_attribute_value
VALUES
    (1, 1, 0, "Xanh"),
    (2, 1, 0, "Đỏ"),
    (3, 1, 0, "Tím"),
    (4, 1, 0, "Vàng"),
    (5, 1, 0, "Hồng"),
    (6, 1, 0, "Nâu"),
    (7, 1, 0, "Trắng"),
    (8, 1, 0, "Đen"),
    (9, 2, 0, "S"),
    (10, 2, 0, "M"),
    (11, 2, 0, "L"),
    (12, 2, 0, "XL"),
    (13, 2, 0, "2XL"),
    (14, 2, 0, "3XL"),
    (15, 4, 0, "Xanh"),
    (16, 4, 0, "Đỏ"),
    (17, 4, 0, "Tím"),
    (18, 4, 0, "Vàng"),
    (19, 4, 0, "Hồng"),
    (20, 4, 0, "Nâu"),
    (21, 4, 0, "Trắng"),
    (22, 4, 0, "Đen"),
    (23, 5, 0, "S"),
    (24, 5, 0, "M"),
    (25, 5, 0, "L"),
    (26, 5, 0, "XL"),
    (27, 5, 0, "2XL"),
    (28, 5, 0, "3XL")

INSERT INTO tbl_category
VALUES
    (1, "Balo & Túi Ví Nam"),
    (2, "Bách Hóa Online"),
    (3, "Chăm sóc thú cưng"),
    (4, "Dụng cụ và thiết bị tiện ích"),
    (5, "Giày Dép Nam"),
    (6, "Giày Dép Nữ"),
    (7, "Giặt giũ & Chăm Sóc Nhà Cửa"),
    (8, "Máy Tính & Laptop"),
    (9, "Máy Ảnh & Máy Quay Phim"),
    (10, "Mẹ & Bé"),
    (11, "Nhà Cửa & Đời Sống"),
    (12, "Nhà Sách Online"),
    (13, "Phụ Kiện & Trang Sức Nữ"),
    (14, "Sắc Đẹp"),
    (15, "Sức Khỏe"),
    (16, "Thiết Bị Điện Gia Dụng"),
    (17, "Thiết Bị Điện Tử"),
    (18, "Thể Thao & Du Lịch"),
    (19, "Thời Trang Nam"),
    (20, "Thời Trang Nữ"),
    (21, "Thời Trang Trẻ Em"),
    (22, "Túi Ví Nữ"),
    (23, "Voucher & Dịch Vụ"),
    (24, "Ô Tô & Xe Máy & Xe Đạp"),
    (25, "Điện Thoại & Phụ Kiện"),
    (26, "Đồ Chơi"),
    (27, "Đồng Hồ")